import { test, expect } from "@playwright/test";

test("street entry without selection restores the user's aerial camera", async ({ page }) => {
  await page.goto("http://127.0.0.1:3100");
  await page.getByRole("button", { name: "3D Provisional", exact: true }).click();
  const scene = page.locator("[data-scene-mode]");
  await expect(scene).toHaveAttribute("data-camera-transition", "ready", { timeout: 60000 });
  const canvas = (await page.locator("canvas").boundingBox())!;
  await page.mouse.move(canvas.x + canvas.width / 2, canvas.y + canvas.height / 2);
  await page.mouse.down();
  await page.mouse.move(canvas.x + canvas.width / 2 + 90, canvas.y + canvas.height / 2 + 20, { steps: 12 });
  await page.mouse.up();
  await page.waitForTimeout(8000); // Software WebGL needs time for frame-based orbit damping to settle.
  const position = () => page.locator("[data-walk-x]").evaluate((el) => ["x", "y", "z"].map((axis) => Number(el.getAttribute(`data-walk-${axis}`))));
  const before = await position();
  expect(Math.abs(before[0] - 80)).toBeGreaterThan(1);
  await page.getByRole("button", { name: "Jelajahi Jalan", exact: true }).click();
  await expect(scene).toHaveAttribute("data-scene-mode", "STREET_EXPLORE");
  await expect(scene).toHaveAttribute("data-camera-transition", "ready");
  const street = await position();
  expect(street[1]).toBeLessThan(1);
  await page.keyboard.down("w");
  await expect.poll(async () => { const p = await position(); return Math.hypot(p[0] - street[0], p[2] - street[2]); }).toBeGreaterThan(0.1);
  await page.keyboard.up("w");
  await page.getByRole("button", { name: "← Kembali ke Peta", exact: true }).last().click();
  await expect(scene).toHaveAttribute("data-camera-transition", "ready");
  const after = await position();
  after.forEach((value, index) => expect(value).toBeCloseTo(before[index], 1));
});

test("immediate resident modal, conflicts, shared selection and provisional WebGL", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("http://127.0.0.1:3100");
  const lot = page.locator('polygon[aria-label^="NHB-6/12,"]');
  await expect(lot).toBeVisible();
  await expect(page.locator("canvas")).toHaveCount(0);
  await lot.click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog").getByText("Warga Uji", { exact: true })).toBeVisible();
  await expect(page.getByRole("dialog").getByText("Iuran: Lunas", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "3D Provisional", exact: true }).click();
  await expect(page.locator("canvas")).toBeVisible({ timeout: 60000 });
  await expect(page.locator('[data-camera-transition]')).toHaveAttribute("data-camera-transition", "ready");
  await expect(page.getByText("validationState=provisional")).toBeVisible();
  await expect(page.getByText("previewKey:")).toContainText("NAHARA BARAT 6");
  await page.screenshot({ path: "/private/tmp/nahara-provisional-3d.png", fullPage: true });
  // Select a different lot in 3D to prove that selection flows back to 2D.
  const { SITEPLAN_LOT_POLYGONS } = await import("../lib/nahara/provisional-lots");
  const { previewPlacement } = await import("../lib/nahara/provisional-3d");
  const { PerspectiveCamera, Vector3 } = await import("three");
  const p = previewPlacement(SITEPLAN_LOT_POLYGONS.find((lot) => lot.blokKey === "NAHARA BARAT 6 10")!);
  const canvas = (await page.locator("canvas").boundingBox())!;
  const camera = new PerspectiveCamera(45, canvas.width / canvas.height, 0.1, 500);
  camera.position.set(80, 100, 100);
  camera.lookAt(0, 0, 0);
  camera.updateMatrixWorld();
  const target = new Vector3(p.position.x, p.box.height, p.position.z).project(camera);
  await page.mouse.click(canvas.x + (target.x + 1) * canvas.width / 2, canvas.y + (1 - target.y) * canvas.height / 2);
  await expect(page.getByRole("dialog").getByText("Warga 3D", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "2D Map", exact: true }).click();
  await expect(page.locator('polygon[aria-label^="NHB-6/10,"]')).toHaveAttribute("aria-pressed", "true");
  await expect(lot).toHaveAttribute("aria-pressed", "false");
  const conflicts = page.locator('polygon[aria-label^="NHT-8/16,"]');
  await expect(conflicts).toHaveCount(2);
  await conflicts.nth(1).focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("dialog").getByText("Warga Konflik", { exact: true })).toBeVisible();
  await expect(page.getByRole("dialog").getByText(/Nomor 16 muncul dua kali/)).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(conflicts.nth(0)).toHaveAttribute("aria-pressed", "false");
  await expect(conflicts.nth(1)).toHaveAttribute("aria-pressed", "true");
  await page.locator('polygon[aria-label^="NHB-8/28,"]').focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("dialog").getByText(/Data hunian.*belum tersedia/)).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await lot.tap();
  await expect(page.getByRole("dialog").getByText("Warga Uji", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).tap();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("button", { name: "3D Provisional", exact: true }).tap();
  await expect(page.locator("canvas")).toBeVisible();
  await page.screenshot({ path: "/private/tmp/nahara-provisional-3d-mobile.png", fullPage: true });
  expect(errors).toEqual([]);
});

test("focus, safe street entry, keyboard movement, modal pause and mobile joystick", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("http://127.0.0.1:3100");
  await page.locator('polygon[aria-label^="NHB-6/12,"]').click();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await page.getByRole("button", { name: "3D Provisional", exact: true }).click();
  const scene = page.locator("[data-scene-mode]");
  const ready = async () => { await expect(scene).toHaveAttribute("data-camera-transition", "ready", { timeout: 15000 }); };
  await ready();
  await page.getByRole("button", { name: "Fokus Rumah", exact: true }).click();
  await expect(scene).toHaveAttribute("data-scene-mode", "HOUSE_FOCUS");
  await ready();
  await page.screenshot({ path: "/private/tmp/nahara-house-focus.png", fullPage: true });
  await page.getByRole("button", { name: "Jelajahi Sekitar", exact: true }).click();
  await expect(scene).toHaveAttribute("data-scene-mode", "STREET_EXPLORE");
  await ready();
  const readPosition = async () => page.locator("[data-walk-x]").evaluate((el) => [
    Number(el.getAttribute("data-walk-x")), Number(el.getAttribute("data-walk-y")), Number(el.getAttribute("data-walk-z")),
  ]);
  const { SITEPLAN_LOT_POLYGONS } = await import("../lib/nahara/provisional-lots");
  const { previewPlacement } = await import("../lib/nahara/provisional-3d");
  const { createWalkNetwork } = await import("../lib/nahara/walk-network");
  const network = createWalkNetwork(SITEPLAN_LOT_POLYGONS.map(previewPlacement));
  const start = await readPosition();
  expect(start[1]).toBeCloseTo(network.eyeHeight, 6);
  expect(network.canWalk(start[0], start[2])).toBe(true);
  await expect(page.getByRole("button", { name: "Lihat Rumah (E)", exact: true })).toBeVisible();
  await page.keyboard.press("e");
  await expect(page.getByRole("dialog").getByText("Warga Uji", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(scene).toHaveAttribute("data-scene-mode", "STREET_EXPLORE");
  await expect(scene).toHaveAttribute("data-camera-transition", "ready");
  expect(await readPosition()).toEqual(start);
  await page.keyboard.down("d");
  await expect.poll(async () => { const p = await readPosition(); return Math.hypot(p[0] - start[0], p[2] - start[2]); }).toBeGreaterThan(0.08);
  await page.keyboard.up("d");
  const moved = await readPosition(); expect(network.canWalk(moved[0], moved[2])).toBe(true);
  // A canvas gesture captures the mouse without selecting a house.
  const canvasRect = (await page.locator("canvas").boundingBox())!;
  await page.mouse.move(canvasRect.x + canvasRect.width * 0.25, canvasRect.y + canvasRect.height * 0.5);
  await page.mouse.down();
  await page.mouse.move(canvasRect.x + canvasRect.width * 0.25 + 390, canvasRect.y + canvasRect.height * 0.5, { steps: 12 });
  await page.mouse.up();
  await expect.poll(() => page.evaluate(() => !!document.pointerLockElement)).toBe(true);
  await expect(page.getByRole("dialog")).toHaveCount(0);
  const turned = await readPosition();
  await page.keyboard.down("Shift"); await page.keyboard.down("w");
  await expect.poll(async () => { const p = await readPosition(); return Math.hypot(p[0] - turned[0], p[2] - turned[2]); }).toBeGreaterThan(0.3);
  await page.keyboard.up("w"); await page.keyboard.up("Shift");
  const sprinted = await readPosition(); expect(network.canWalk(sprinted[0], sprinted[2])).toBe(true);
  await page.screenshot({ path: "/private/tmp/nahara-street-view.png", fullPage: true });
  await page.keyboard.press("Escape");
  await expect.poll(() => page.evaluate(() => !!document.pointerLockElement)).toBe(false);
  // A resident modal pauses walking, even if movement keys are pressed.
  await page.getByRole("button", { name: "Lihat data alamat NHB-6/12", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  const paused = await readPosition();
  await page.keyboard.down("w");
  await page.waitForTimeout(400);
  await page.keyboard.up("w");
  expect(await readPosition()).toEqual(paused);
  await page.getByRole("button", { name: "Tutup detail", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("group", { name: "Joystick jalan" }).scrollIntoViewIfNeeded();
  const joystick = (await page.getByRole("group", { name: "Joystick jalan" }).boundingBox())!;
  const touch = await page.context().newCDPSession(page);
  const x = joystick.x + joystick.width / 2, y = joystick.y + joystick.height / 2;
  const beforeTouch = await readPosition();
  await touch.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x, y }] });
  await touch.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: x + 38, y }] });
  await expect.poll(async () => { const p = await readPosition(); return Math.hypot(p[0] - beforeTouch[0], p[2] - beforeTouch[2]); }).toBeGreaterThan(0.05);
  await touch.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  const afterTouch = await readPosition(); expect(network.canWalk(afterTouch[0], afterTouch[2])).toBe(true);
  await page.screenshot({ path: "/private/tmp/nahara-street-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "← Kembali ke Peta", exact: true }).last().tap();
  await expect(scene).toHaveAttribute("data-scene-mode", "MASTERPLAN");
  await ready();
  expect((await readPosition())[1]).toBeGreaterThan(50);
  expect(errors).toEqual([]);
});
